-- HERDON Sprint 12A
-- Optional strategic tables used by premium planning modules.
-- Safe to run multiple times.

create table if not exists public.pastagens (
  id bigint generated by default as identity primary key,
  owner_user_id uuid,
  nome text not null default '',
  area_ha numeric default 0,
  capacidade_suporte_ua_ha numeric default 0,
  custo_pasto_r_cab_mes numeric default 0,
  arrendamento_ativo boolean default false,
  area_arrendada_ha numeric default 0,
  custo_arrendamento_mes numeric default 0,
  observacoes text default '',
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.cenarios (
  id bigint generated by default as identity primary key,
  owner_user_id uuid,
  nome text not null default '',
  periodo_inicio date,
  periodo_fim date,
  observacoes text default '',
  status text default 'rascunho',
  compras_simuladas numeric default 0,
  vendas_simuladas numeric default 0,
  mortalidade_pct numeric default 0,
  natalidade_pct numeric default 0,
  valor_medio_venda numeric default 0,
  custo_medio_compra numeric default 0,
  capacidade_suporte_ua numeric default 0,
  area_pastagem_ha numeric default 0,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_pastagens_owner_user_id on public.pastagens(owner_user_id);
create index if not exists idx_cenarios_owner_user_id on public.cenarios(owner_user_id);
