-- HERDON production schema bundle
-- Order: run this file first, then docs/supabase-production-rls.sql
-- Scope: tables used by the current production runtime.
-- Local-only structures intentionally not provisioned here:
--   - db.suplementacao / dietas (UI-local nutrition planning state, no Supabase persistence helper today)
-- Subscription/billing structures included here for the internal SaaS gate:
--   - subscription_plans
--   - customer_subscriptions
--   - billing_events
--   - checkout_sessions

create extension if not exists citext;
create extension if not exists pgcrypto;

do $$
begin
  if not exists (
    select 1
    from pg_type
    where typname = 'app_profile'
      and typnamespace = 'public'::regnamespace
  ) then
    create type public.app_profile as enum ('proprietario', 'gerente', 'operador', 'visualizador');
  end if;
end $$;

create or replace function public.set_current_timestamp_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  owner_user_id uuid references auth.users (id) on delete set null,
  email citext not null,
  nome text,
  perfil public.app_profile not null default 'visualizador',
  telefone text,
  cargo text,
  foto_url text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists profiles_email_unique_idx on public.profiles (email);
create index if not exists profiles_owner_user_id_idx on public.profiles (owner_user_id);
create index if not exists profiles_created_at_idx on public.profiles (created_at desc);
create index if not exists profiles_updated_at_idx on public.profiles (updated_at desc);

create table if not exists public.invites (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  email citext not null,
  nome text,
  perfil public.app_profile not null default 'visualizador',
  status text not null default 'pendente',
  notes text,
  created_by uuid references auth.users (id) on delete set null,
  used_by uuid references auth.users (id) on delete set null,
  used_at timestamptz,
  canceled_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint invites_status_check check (status in ('pendente', 'ativo', 'aceito', 'enviado', 'utilizado', 'cancelado', 'expirado'))
);

create unique index if not exists invites_owner_email_unique_idx on public.invites (owner_user_id, email);
create index if not exists invites_status_idx on public.invites (status);
create index if not exists invites_created_by_idx on public.invites (created_by);
create index if not exists invites_used_by_idx on public.invites (used_by);
create index if not exists invites_created_at_idx on public.invites (created_at desc);
create index if not exists invites_updated_at_idx on public.invites (updated_at desc);

create table if not exists public.subscription_plans (
  id bigint generated by default as identity primary key,
  plan_code text not null,
  plan_name text not null,
  status text not null default 'active',
  billing_provider text not null default 'manual',
  price_cents integer,
  currency_code text not null default 'BRL',
  billing_interval text not null default 'month',
  description text,
  sort_order integer not null default 0,
  is_launch_offer boolean not null default false,
  easy_to_disable boolean not null default false,
  plan_entitlements jsonb not null default '{}'::jsonb,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint subscription_plans_status_check check (status in ('active', 'inactive', 'hidden'))
);

create unique index if not exists subscription_plans_plan_code_unique_idx on public.subscription_plans (plan_code);
create index if not exists subscription_plans_status_idx on public.subscription_plans (status);
create index if not exists subscription_plans_sort_order_idx on public.subscription_plans (sort_order);
create index if not exists subscription_plans_created_at_idx on public.subscription_plans (created_at desc);
create index if not exists subscription_plans_updated_at_idx on public.subscription_plans (updated_at desc);

insert into public.subscription_plans (
  plan_code,
  plan_name,
  status,
  billing_provider,
  price_cents,
  currency_code,
  billing_interval,
  description,
  sort_order,
  is_launch_offer,
  easy_to_disable,
  plan_entitlements,
  raw_payload
)
values
  (
    'fundador',
    'FUNDADOR',
    'active',
    'manual',
    29700,
    'BRL',
    'month',
    'Oferta de lançamento com acesso completo.',
    1,
    true,
    true,
    '{"fullAccess": true, "limits": {"farms": 50, "animals": 10000, "users": 50}, "modules": ["*"]}'::jsonb,
    '{}'::jsonb
  ),
  (
    'essencial',
    'ESSENCIAL',
    'active',
    'manual',
    19700,
    'BRL',
    'month',
    'Plano para operação enxuta e organizada.',
    2,
    false,
    false,
    '{"fullAccess": false, "limits": {"farms": 1, "animals": 300, "users": 2}, "modules": ["dashboard", "fazendas", "lotes", "animais", "pesagens", "tarefas", "calendarioOperacional", "rotina", "perfil", "configuracoes", "resultados", "comparativo"]}'::jsonb,
    '{}'::jsonb
  ),
  (
    'pro',
    'PRO',
    'active',
    'manual',
    39700,
    'BRL',
    'month',
    'Plano completo para a operação diária da fazenda.',
    3,
    false,
    false,
    '{"fullAccess": false, "limits": {"farms": 3, "animals": 1000, "users": 5}, "modules": ["dashboard", "fazendas", "lotes", "animais", "pesagens", "tarefas", "calendarioOperacional", "rotina", "perfil", "configuracoes", "resultados", "comparativo", "financeiro", "estoque", "sanitario", "relatoriosGerenciais"]}'::jsonb,
    '{}'::jsonb
  ),
  (
    'premium',
    'PREMIUM',
    'active',
    'manual',
    69700,
    'BRL',
    'month',
    'Plano avançado para gestão ampliada e indicadores.',
    4,
    false,
    false,
    '{"fullAccess": false, "limits": {"farms": 10, "animals": 3000, "users": 10}, "modules": ["dashboard", "fazendas", "lotes", "animais", "pesagens", "tarefas", "calendarioOperacional", "rotina", "perfil", "configuracoes", "resultados", "comparativo", "financeiro", "estoque", "sanitario", "relatoriosGerenciais", "pastagens", "indicadores", "cenarios", "dashboardPremium", "evolucaoRebanho"]}'::jsonb,
    '{}'::jsonb
  ),
  (
    'enterprise',
    'ENTERPRISE',
    'active',
    'manual',
    null,
    'BRL',
    'custom',
    'Plano personalizado com ativação sob consulta.',
    5,
    false,
    false,
    '{"fullAccess": true, "customLimits": true, "limits": {"farms": null, "animals": null, "users": null}, "modules": ["*"]}'::jsonb,
    '{}'::jsonb
  )
on conflict (plan_code) do update set
  plan_name = excluded.plan_name,
  status = excluded.status,
  billing_provider = excluded.billing_provider,
  price_cents = excluded.price_cents,
  currency_code = excluded.currency_code,
  billing_interval = excluded.billing_interval,
  description = excluded.description,
  sort_order = excluded.sort_order,
  is_launch_offer = excluded.is_launch_offer,
  easy_to_disable = excluded.easy_to_disable,
  plan_entitlements = excluded.plan_entitlements,
  raw_payload = excluded.raw_payload;

create table if not exists public.customer_subscriptions (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  user_id uuid references auth.users (id) on delete set null,
  farm_id bigint references public.fazendas (id) on delete set null,
  fazenda_id bigint references public.fazendas (id) on delete set null,
  plan_code text not null references public.subscription_plans (plan_code) on update cascade,
  plan_name text,
  status text not null default 'trialing',
  billing_provider text not null default 'manual',
  provider_customer_id text,
  provider_subscription_id text,
  provider_payment_id text,
  current_period_start timestamptz,
  current_period_end timestamptz,
  trial_ends_at timestamptz,
  canceled_at timestamptz,
  blocked_at timestamptz,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint customer_subscriptions_status_check check (status in ('trialing', 'active', 'past_due', 'canceled', 'blocked', 'internal_test'))
);

create unique index if not exists customer_subscriptions_provider_subscription_id_unique_idx on public.customer_subscriptions (provider_subscription_id) where provider_subscription_id is not null;
create index if not exists customer_subscriptions_owner_user_id_idx on public.customer_subscriptions (owner_user_id);
create index if not exists customer_subscriptions_user_id_idx on public.customer_subscriptions (user_id);
create index if not exists customer_subscriptions_plan_code_idx on public.customer_subscriptions (plan_code);
create index if not exists customer_subscriptions_status_idx on public.customer_subscriptions (status);
create index if not exists customer_subscriptions_created_at_idx on public.customer_subscriptions (created_at desc);
create index if not exists customer_subscriptions_updated_at_idx on public.customer_subscriptions (updated_at desc);

create table if not exists public.billing_events (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  user_id uuid references auth.users (id) on delete set null,
  subscription_id bigint references public.customer_subscriptions (id) on delete set null,
  event_type text not null,
  event_status text not null default 'received',
  billing_provider text not null default 'manual',
  provider_event_id text,
  provider_customer_id text,
  provider_subscription_id text,
  provider_payment_id text,
  occurred_at timestamptz,
  processed_at timestamptz,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists billing_events_owner_user_id_idx on public.billing_events (owner_user_id);
create index if not exists billing_events_subscription_id_idx on public.billing_events (subscription_id);
create index if not exists billing_events_event_type_idx on public.billing_events (event_type);
create index if not exists billing_events_created_at_idx on public.billing_events (created_at desc);
create index if not exists billing_events_updated_at_idx on public.billing_events (updated_at desc);

create table if not exists public.checkout_sessions (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  user_id uuid references auth.users (id) on delete set null,
  plan_code text references public.subscription_plans (plan_code) on update cascade,
  status text not null default 'pending',
  billing_provider text not null default 'manual',
  provider_checkout_session_id text,
  checkout_url text,
  expires_at timestamptz,
  completed_at timestamptz,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint checkout_sessions_status_check check (status in ('pending', 'completed', 'expired', 'canceled', 'failed'))
);

create unique index if not exists checkout_sessions_provider_checkout_session_id_unique_idx on public.checkout_sessions (provider_checkout_session_id) where provider_checkout_session_id is not null;
create index if not exists checkout_sessions_owner_user_id_idx on public.checkout_sessions (owner_user_id);
create index if not exists checkout_sessions_plan_code_idx on public.checkout_sessions (plan_code);
create index if not exists checkout_sessions_status_idx on public.checkout_sessions (status);
create index if not exists checkout_sessions_created_at_idx on public.checkout_sessions (created_at desc);
create index if not exists checkout_sessions_updated_at_idx on public.checkout_sessions (updated_at desc);

create table if not exists public.fazendas (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  cloud_id uuid,
  nome text not null,
  proprietario text,
  responsavel text,
  cidade text,
  estado text,
  area_total_ha numeric(14, 2),
  area_pastagem_ha numeric(14, 2),
  capacidade_ua numeric(14, 2),
  tipo_producao text,
  inscricao_estadual text,
  cnpj_cpf text,
  telefone text,
  email text,
  endereco text,
  status text default 'ativa',
  observacoes text,
  hectares numeric(14, 2),
  area numeric(14, 2),
  hectares_pastagem numeric(14, 2),
  capacidade_lotacao numeric(14, 2),
  synced_from text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists fazendas_cloud_id_unique_idx on public.fazendas (cloud_id) where cloud_id is not null;
create index if not exists fazendas_owner_user_id_idx on public.fazendas (owner_user_id);
create index if not exists fazendas_nome_idx on public.fazendas (nome);
create index if not exists fazendas_created_at_idx on public.fazendas (created_at desc);
create index if not exists fazendas_updated_at_idx on public.fazendas (updated_at desc);

create table if not exists public.pastagens (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  fazenda_id bigint references public.fazendas (id) on delete set null,
  faz_id bigint references public.fazendas (id) on delete set null,
  nome text not null,
  area_ha numeric(14, 2),
  capacidade_suporte_ua_ha numeric(14, 4),
  status text default 'ativo',
  observacoes text,
  obs text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists pastagens_owner_user_id_idx on public.pastagens (owner_user_id);
create index if not exists pastagens_fazenda_id_idx on public.pastagens (fazenda_id);
create index if not exists pastagens_faz_id_idx on public.pastagens (faz_id);
create index if not exists pastagens_created_at_idx on public.pastagens (created_at desc);
create index if not exists pastagens_updated_at_idx on public.pastagens (updated_at desc);

create table if not exists public.lotes (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  cloud_id uuid,
  nome text not null,
  faz_id bigint references public.fazendas (id) on delete set null,
  pastagem_id bigint references public.pastagens (id) on delete set null,
  entrada date,
  saida date,
  status text default 'ativo',
  tipo text,
  sistema text,
  categoria_animal text,
  categoria text,
  raca text,
  sexo text,
  qtd numeric(14, 2),
  p_ini numeric(14, 3),
  p_at numeric(14, 3),
  peso_alvo numeric(14, 3),
  gmd_meta numeric(14, 4),
  investimento numeric(14, 2),
  custo_fixo_mensal numeric(14, 2),
  preco_arroba numeric(14, 2),
  rendimento_carcaca numeric(8, 3),
  dias_estimados numeric(14, 2),
  consumo_tipo text,
  consumo_por_cabeca_dia numeric(14, 4),
  consumo_total_estimado numeric(14, 4),
  custo_total_estimado numeric(14, 2),
  preco_kg numeric(14, 4),
  supl_nome text,
  supl_rkg numeric(14, 4),
  supl_pv_pct numeric(14, 4),
  supl_meta_dias numeric(14, 2),
  ultima_pesagem date,
  data_saida date,
  data_venda date,
  data_encerramento date,
  fechamento jsonb,
  obs text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists lotes_cloud_id_unique_idx on public.lotes (cloud_id) where cloud_id is not null;
create index if not exists lotes_owner_user_id_idx on public.lotes (owner_user_id);
create index if not exists lotes_faz_id_idx on public.lotes (faz_id);
create index if not exists lotes_pastagem_id_idx on public.lotes (pastagem_id);
create index if not exists lotes_status_idx on public.lotes (status);
create index if not exists lotes_created_at_idx on public.lotes (created_at desc);
create index if not exists lotes_updated_at_idx on public.lotes (updated_at desc);

create table if not exists public.animais (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  cloud_id uuid,
  fazenda_id bigint references public.fazendas (id) on delete set null,
  lote_id bigint references public.lotes (id) on delete set null,
  identificacao text not null,
  nome text,
  tipo_registro text default 'individual',
  categoria text,
  categoria_animal text,
  raca text,
  sexo text,
  origem text,
  qtd numeric(14, 2),
  p_ini numeric(14, 3),
  p_at numeric(14, 3),
  dias numeric(14, 2),
  consumo numeric(14, 4),
  status text default 'ativo',
  data_referencia date,
  data_nascimento date,
  data_saida date,
  data_venda date,
  observacao text,
  rendimento_carcaca numeric(8, 3),
  preco_arroba numeric(14, 2),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists animais_cloud_id_unique_idx on public.animais (cloud_id) where cloud_id is not null;
create index if not exists animais_owner_user_id_idx on public.animais (owner_user_id);
create index if not exists animais_fazenda_id_idx on public.animais (fazenda_id);
create index if not exists animais_lote_id_idx on public.animais (lote_id);
create index if not exists animais_status_idx on public.animais (status);
create index if not exists animais_created_at_idx on public.animais (created_at desc);
create index if not exists animais_updated_at_idx on public.animais (updated_at desc);

create table if not exists public.pesagens (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  cloud_id uuid,
  lote_id bigint references public.lotes (id) on delete set null,
  animal_id bigint references public.animais (id) on delete set null,
  data date,
  peso_medio numeric(14, 3),
  tipo text,
  origem text,
  rendimento_carcaca numeric(8, 3),
  preco_arroba numeric(14, 2),
  observacao text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists pesagens_cloud_id_unique_idx on public.pesagens (cloud_id) where cloud_id is not null;
create index if not exists pesagens_owner_user_id_idx on public.pesagens (owner_user_id);
create index if not exists pesagens_lote_id_idx on public.pesagens (lote_id);
create index if not exists pesagens_animal_id_idx on public.pesagens (animal_id);
create index if not exists pesagens_data_idx on public.pesagens (data desc);
create index if not exists pesagens_created_at_idx on public.pesagens (created_at desc);
create index if not exists pesagens_updated_at_idx on public.pesagens (updated_at desc);

create table if not exists public.sanitario (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  fazenda_id bigint references public.fazendas (id) on delete set null,
  lote_id bigint references public.lotes (id) on delete set null,
  tipo text,
  nome text,
  desc text,
  data_aplic date,
  proxima date,
  alerta_dias_antes integer,
  qtd numeric(14, 2),
  obs text,
  funcionario_responsavel_id bigint,
  rotina_automatica_id bigint,
  status text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists sanitario_owner_user_id_idx on public.sanitario (owner_user_id);
create index if not exists sanitario_fazenda_id_idx on public.sanitario (fazenda_id);
create index if not exists sanitario_lote_id_idx on public.sanitario (lote_id);
create index if not exists sanitario_funcionario_responsavel_id_idx on public.sanitario (funcionario_responsavel_id);
create index if not exists sanitario_data_aplic_idx on public.sanitario (data_aplic desc);
create index if not exists sanitario_proxima_idx on public.sanitario (proxima desc);
create index if not exists sanitario_created_at_idx on public.sanitario (created_at desc);
create index if not exists sanitario_updated_at_idx on public.sanitario (updated_at desc);

create table if not exists public.estoque (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  fazenda_id bigint references public.fazendas (id) on delete set null,
  nome text,
  produto text,
  categoria text,
  subcategoria text,
  unidade text,
  unidade_medida text,
  quantidade numeric(14, 4),
  quantidade_atual numeric(14, 4),
  quantidade_minima numeric(14, 4),
  custo_unitario numeric(14, 4),
  valor_unitario numeric(14, 4),
  preco_unitario numeric(14, 4),
  valor_total numeric(14, 2),
  validade date,
  data_validade date,
  fornecedor text,
  observacoes text,
  obs text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists estoque_owner_user_id_idx on public.estoque (owner_user_id);
create index if not exists estoque_fazenda_id_idx on public.estoque (fazenda_id);
create index if not exists estoque_categoria_idx on public.estoque (categoria);
create index if not exists estoque_created_at_idx on public.estoque (created_at desc);
create index if not exists estoque_updated_at_idx on public.estoque (updated_at desc);

create table if not exists public.movimentacoes_estoque (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  item_estoque_id bigint references public.estoque (id) on delete set null,
  lote_id bigint references public.lotes (id) on delete set null,
  tipo text not null,
  quantidade numeric(14, 4) not null,
  data date,
  valor_total numeric(14, 2),
  fornecedor text,
  numero_nf text,
  obs text,
  origem text,
  origem_tipo text,
  origem_id bigint,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists movimentacoes_estoque_owner_user_id_idx on public.movimentacoes_estoque (owner_user_id);
create index if not exists movimentacoes_estoque_item_idx on public.movimentacoes_estoque (item_estoque_id);
create index if not exists movimentacoes_estoque_lote_idx on public.movimentacoes_estoque (lote_id);
create index if not exists movimentacoes_estoque_data_idx on public.movimentacoes_estoque (data desc);
create index if not exists movimentacoes_estoque_created_at_idx on public.movimentacoes_estoque (created_at desc);
create index if not exists movimentacoes_estoque_updated_at_idx on public.movimentacoes_estoque (updated_at desc);

create table if not exists public.movimentacoes_financeiras (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  fazenda_id bigint references public.fazendas (id) on delete set null,
  lote_id bigint references public.lotes (id) on delete set null,
  tipo text not null,
  categoria text,
  subcategoria text,
  descricao text,
  valor numeric(14, 2) not null default 0,
  data date,
  data_vencimento date,
  metodo_pagamento text,
  pago boolean default false,
  comprador text,
  fornecedor text,
  observacao text,
  origem text,
  origem_tipo text,
  origem_id bigint,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists movimentacoes_financeiras_owner_user_id_idx on public.movimentacoes_financeiras (owner_user_id);
create index if not exists movimentacoes_financeiras_fazenda_id_idx on public.movimentacoes_financeiras (fazenda_id);
create index if not exists movimentacoes_financeiras_lote_id_idx on public.movimentacoes_financeiras (lote_id);
create index if not exists movimentacoes_financeiras_data_idx on public.movimentacoes_financeiras (data desc);
create index if not exists movimentacoes_financeiras_created_at_idx on public.movimentacoes_financeiras (created_at desc);
create index if not exists movimentacoes_financeiras_updated_at_idx on public.movimentacoes_financeiras (updated_at desc);

create table if not exists public.movimentacoes_animais (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  lote_id bigint references public.lotes (id) on delete set null,
  destino_lote_id bigint references public.lotes (id) on delete set null,
  animal_id bigint references public.animais (id) on delete set null,
  tipo text not null,
  qtd numeric(14, 2),
  peso_medio numeric(14, 3),
  valor_total numeric(14, 2),
  custo_por_cabeca numeric(14, 4),
  comprador_fornecedor text,
  data date,
  obs text,
  origem text,
  origem_tipo text,
  origem_id bigint,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists movimentacoes_animais_owner_user_id_idx on public.movimentacoes_animais (owner_user_id);
create index if not exists movimentacoes_animais_lote_id_idx on public.movimentacoes_animais (lote_id);
create index if not exists movimentacoes_animais_destino_lote_id_idx on public.movimentacoes_animais (destino_lote_id);
create index if not exists movimentacoes_animais_animal_id_idx on public.movimentacoes_animais (animal_id);
create index if not exists movimentacoes_animais_data_idx on public.movimentacoes_animais (data desc);
create index if not exists movimentacoes_animais_created_at_idx on public.movimentacoes_animais (created_at desc);
create index if not exists movimentacoes_animais_updated_at_idx on public.movimentacoes_animais (updated_at desc);

create table if not exists public.custos (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  fazenda_id bigint references public.fazendas (id) on delete set null,
  lote_id bigint references public.lotes (id) on delete set null,
  cat text,
  val numeric(14, 2),
  data date,
  desc text,
  observacao text,
  origem text,
  origem_id bigint,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists custos_owner_user_id_idx on public.custos (owner_user_id);
create index if not exists custos_fazenda_id_idx on public.custos (fazenda_id);
create index if not exists custos_lote_id_idx on public.custos (lote_id);
create index if not exists custos_data_idx on public.custos (data desc);
create index if not exists custos_created_at_idx on public.custos (created_at desc);
create index if not exists custos_updated_at_idx on public.custos (updated_at desc);

create table if not exists public.funcionarios (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  fazenda_id bigint references public.fazendas (id) on delete set null,
  nome text not null,
  cargo text,
  funcao text,
  telefone text,
  email text,
  status text default 'ativo',
  observacoes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists funcionarios_owner_user_id_idx on public.funcionarios (owner_user_id);
create index if not exists funcionarios_fazenda_id_idx on public.funcionarios (fazenda_id);
create index if not exists funcionarios_status_idx on public.funcionarios (status);
create index if not exists funcionarios_created_at_idx on public.funcionarios (created_at desc);
create index if not exists funcionarios_updated_at_idx on public.funcionarios (updated_at desc);

create table if not exists public.rotinas (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  fazenda_id bigint references public.fazendas (id) on delete set null,
  funcionario_id bigint references public.funcionarios (id) on delete set null,
  lote_id bigint references public.lotes (id) on delete set null,
  tarefa text not null,
  setor text,
  descricao text,
  obs text,
  recorrente boolean not null default false,
  recorrencia_tipo text,
  dias_semana jsonb not null default '[]'::jsonb,
  data date,
  data_inicio date,
  data_fim date,
  status text default 'pendente',
  concluido_datas jsonb not null default '[]'::jsonb,
  origem_sistema text,
  origem_sanitario_id bigint references public.sanitario (id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists rotinas_owner_user_id_idx on public.rotinas (owner_user_id);
create index if not exists rotinas_fazenda_id_idx on public.rotinas (fazenda_id);
create index if not exists rotinas_funcionario_id_idx on public.rotinas (funcionario_id);
create index if not exists rotinas_lote_id_idx on public.rotinas (lote_id);
create index if not exists rotinas_data_idx on public.rotinas (data desc);
create index if not exists rotinas_created_at_idx on public.rotinas (created_at desc);
create index if not exists rotinas_updated_at_idx on public.rotinas (updated_at desc);

create table if not exists public.tarefas (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  fazenda_id bigint references public.fazendas (id) on delete set null,
  lote_id bigint references public.lotes (id) on delete set null,
  responsavel_id bigint references public.funcionarios (id) on delete set null,
  titulo text not null,
  descricao text,
  prioridade text,
  categoria text,
  status text default 'pendente',
  data_vencimento date,
  concluida_em timestamptz,
  adiado_em timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists tarefas_owner_user_id_idx on public.tarefas (owner_user_id);
create index if not exists tarefas_fazenda_id_idx on public.tarefas (fazenda_id);
create index if not exists tarefas_lote_id_idx on public.tarefas (lote_id);
create index if not exists tarefas_responsavel_id_idx on public.tarefas (responsavel_id);
create index if not exists tarefas_created_at_idx on public.tarefas (created_at desc);
create index if not exists tarefas_updated_at_idx on public.tarefas (updated_at desc);

create table if not exists public.usuarios (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  nome text,
  email text,
  perfil text,
  status text,
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists usuarios_owner_user_id_idx on public.usuarios (owner_user_id);
create index if not exists usuarios_email_idx on public.usuarios (email);
create index if not exists usuarios_created_at_idx on public.usuarios (created_at desc);
create index if not exists usuarios_updated_at_idx on public.usuarios (updated_at desc);

create table if not exists public.configuracoes (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  fazenda_selecionada_id bigint references public.fazendas (id) on delete set null,
  geral jsonb not null default '{}'::jsonb,
  notificacoes jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists configuracoes_owner_user_id_unique_idx on public.configuracoes (owner_user_id);
create index if not exists configuracoes_fazenda_selecionada_id_idx on public.configuracoes (fazenda_selecionada_id);
create index if not exists configuracoes_created_at_idx on public.configuracoes (created_at desc);
create index if not exists configuracoes_updated_at_idx on public.configuracoes (updated_at desc);

create table if not exists public.cenarios (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  fazenda_id bigint references public.fazendas (id) on delete set null,
  lote_id bigint references public.lotes (id) on delete set null,
  nome text not null,
  periodo_inicio date,
  periodo_fim date,
  observacoes text,
  status text,
  compras_simuladas numeric(14, 2),
  vendas_simuladas numeric(14, 2),
  mortalidade_pct numeric(14, 4),
  natalidade_pct numeric(14, 4),
  valor_medio_venda numeric(14, 2),
  custo_medio_compra numeric(14, 2),
  capacidade_suporte_ua numeric(14, 2),
  area_pastagem_ha numeric(14, 2),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists cenarios_owner_user_id_idx on public.cenarios (owner_user_id);
create index if not exists cenarios_fazenda_id_idx on public.cenarios (fazenda_id);
create index if not exists cenarios_lote_id_idx on public.cenarios (lote_id);
create index if not exists cenarios_created_at_idx on public.cenarios (created_at desc);
create index if not exists cenarios_updated_at_idx on public.cenarios (updated_at desc);

create table if not exists public.auditoria (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  usuario_id uuid references auth.users (id) on delete set null,
  acao text not null,
  entidade text not null,
  entidade_id text,
  criticidade text,
  detalhes jsonb not null default '{}'::jsonb,
  data_hora timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists auditoria_owner_user_id_idx on public.auditoria (owner_user_id);
create index if not exists auditoria_usuario_id_idx on public.auditoria (usuario_id);
create index if not exists auditoria_data_hora_idx on public.auditoria (data_hora desc);
create index if not exists auditoria_created_at_idx on public.auditoria (created_at desc);
create index if not exists auditoria_updated_at_idx on public.auditoria (updated_at desc);

create table if not exists public.alertas_resolvidos (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  chave text not null,
  ack_key text,
  origem text,
  resolved_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists alertas_resolvidos_owner_chave_unique_idx on public.alertas_resolvidos (owner_user_id, chave);
create index if not exists alertas_resolvidos_created_at_idx on public.alertas_resolvidos (created_at desc);
create index if not exists alertas_resolvidos_updated_at_idx on public.alertas_resolvidos (updated_at desc);

create table if not exists public.alertas_adiados (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  chave text not null,
  ate timestamptz,
  snooze_until timestamptz,
  origem text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists alertas_adiados_owner_chave_unique_idx on public.alertas_adiados (owner_user_id, chave);
create index if not exists alertas_adiados_created_at_idx on public.alertas_adiados (created_at desc);
create index if not exists alertas_adiados_updated_at_idx on public.alertas_adiados (updated_at desc);

create table if not exists public.consumo_suplementacao (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users (id) on delete cascade,
  fazenda_id bigint references public.fazendas (id) on delete set null,
  lote_id bigint references public.lotes (id) on delete set null,
  item_estoque_id bigint references public.estoque (id) on delete set null,
  dieta_id bigint,
  origem_tipo text,
  ref_id bigint,
  produto_nome text,
  dieta_nome text,
  modo text,
  quantidade numeric(14, 4),
  qtd_total numeric(14, 4),
  quantidade_total numeric(14, 4),
  consumo_por_cabeca_dia numeric(14, 4),
  percentual_peso_vivo numeric(14, 4),
  peso_medio_usado numeric(14, 4),
  unidade text,
  custo_total numeric(14, 2),
  data date,
  obs text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists consumo_suplementacao_owner_user_id_idx on public.consumo_suplementacao (owner_user_id);
create index if not exists consumo_suplementacao_fazenda_id_idx on public.consumo_suplementacao (fazenda_id);
create index if not exists consumo_suplementacao_lote_id_idx on public.consumo_suplementacao (lote_id);
create index if not exists consumo_suplementacao_item_estoque_id_idx on public.consumo_suplementacao (item_estoque_id);
create index if not exists consumo_suplementacao_data_idx on public.consumo_suplementacao (data desc);
create index if not exists consumo_suplementacao_created_at_idx on public.consumo_suplementacao (created_at desc);
create index if not exists consumo_suplementacao_updated_at_idx on public.consumo_suplementacao (updated_at desc);

alter table public.sanitario
  drop constraint if exists sanitario_funcionario_responsavel_id_fkey;

alter table public.sanitario
  add constraint sanitario_funcionario_responsavel_id_fkey
  foreign key (funcionario_responsavel_id)
  references public.funcionarios (id)
  on delete set null;

alter table public.sanitario
  drop constraint if exists sanitario_rotina_automatica_id_fkey;

alter table public.sanitario
  add constraint sanitario_rotina_automatica_id_fkey
  foreign key (rotina_automatica_id)
  references public.rotinas (id)
  on delete set null;

create or replace function public.handle_new_user_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  invited_record public.invites%rowtype;
  assigned_profile public.app_profile := 'visualizador';
  resolved_name text;
  resolved_owner_user_id uuid;
begin
  resolved_name := coalesce(
    new.raw_user_meta_data ->> 'nome',
    new.raw_user_meta_data ->> 'name',
    split_part(new.email, '@', 1)
  );

  select *
    into invited_record
  from public.invites
  where lower(email::text) = lower(new.email)
    and status in ('pendente', 'ativo', 'enviado')
  order by created_at desc
  limit 1;

  if invited_record.id is not null then
    assigned_profile := invited_record.perfil;
    resolved_owner_user_id := coalesce(invited_record.owner_user_id, invited_record.created_by, new.id);
  else
    assigned_profile := coalesce(
      nullif(lower(new.raw_user_meta_data ->> 'perfil'), '')::public.app_profile,
      'proprietario'::public.app_profile
    );
    resolved_owner_user_id := new.id;
  end if;

  insert into public.profiles (id, owner_user_id, email, nome, perfil)
  values (new.id, resolved_owner_user_id, new.email, resolved_name, assigned_profile)
  on conflict (id) do update
    set
      owner_user_id = coalesce(public.profiles.owner_user_id, excluded.owner_user_id),
      email = excluded.email,
      nome = coalesce(excluded.nome, public.profiles.nome),
      perfil = coalesce(public.profiles.perfil, excluded.perfil),
      updated_at = timezone('utc', now());

  if invited_record.id is not null then
    update public.invites
      set
        status = 'aceito',
        used_by = new.id,
        used_at = timezone('utc', now()),
        updated_at = timezone('utc', now())
      where id = invited_record.id;
  end if;

  return new;
exception
  when invalid_text_representation then
    insert into public.profiles (id, owner_user_id, email, nome, perfil)
    values (new.id, coalesce(resolved_owner_user_id, new.id), new.email, resolved_name, 'proprietario')
    on conflict (id) do update
      set
        owner_user_id = coalesce(public.profiles.owner_user_id, excluded.owner_user_id),
        email = excluded.email,
        nome = coalesce(excluded.nome, public.profiles.nome),
        updated_at = timezone('utc', now());
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user_profile();

insert into public.profiles (id, owner_user_id, email, nome, perfil)
select
  users.id,
  users.id,
  users.email,
  coalesce(
    users.raw_user_meta_data ->> 'nome',
    users.raw_user_meta_data ->> 'name',
    split_part(users.email, '@', 1)
  ) as nome,
  'proprietario'::public.app_profile as perfil
from auth.users users
left join public.profiles profiles on profiles.id = users.id
where profiles.id is null;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at before update on public.profiles
for each row execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_invites_updated_at on public.invites;
create trigger set_invites_updated_at before update on public.invites
for each row execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_subscription_plans_updated_at on public.subscription_plans;
create trigger set_subscription_plans_updated_at before update on public.subscription_plans
for each row execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_customer_subscriptions_updated_at on public.customer_subscriptions;
create trigger set_customer_subscriptions_updated_at before update on public.customer_subscriptions
for each row execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_billing_events_updated_at on public.billing_events;
create trigger set_billing_events_updated_at before update on public.billing_events
for each row execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_checkout_sessions_updated_at on public.checkout_sessions;
create trigger set_checkout_sessions_updated_at before update on public.checkout_sessions
for each row execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_fazendas_updated_at on public.fazendas;
create trigger set_fazendas_updated_at before update on public.fazendas
for each row execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_pastagens_updated_at on public.pastagens;
create trigger set_pastagens_updated_at before update on public.pastagens
for each row execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_lotes_updated_at on public.lotes;
create trigger set_lotes_updated_at before update on public.lotes
for each row execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_animais_updated_at on public.animais;
create trigger set_animais_updated_at before update on public.animais
for each row execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_pesagens_updated_at on public.pesagens;
create trigger set_pesagens_updated_at before update on public.pesagens
for each row execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_sanitario_updated_at on public.sanitario;
create trigger set_sanitario_updated_at before update on public.sanitario
for each row execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_estoque_updated_at on public.estoque;
create trigger set_estoque_updated_at before update on public.estoque
for each row execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_movimentacoes_estoque_updated_at on public.movimentacoes_estoque;
create trigger set_movimentacoes_estoque_updated_at before update on public.movimentacoes_estoque
for each row execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_movimentacoes_financeiras_updated_at on public.movimentacoes_financeiras;
create trigger set_movimentacoes_financeiras_updated_at before update on public.movimentacoes_financeiras
for each row execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_movimentacoes_animais_updated_at on public.movimentacoes_animais;
create trigger set_movimentacoes_animais_updated_at before update on public.movimentacoes_animais
for each row execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_custos_updated_at on public.custos;
create trigger set_custos_updated_at before update on public.custos
for each row execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_funcionarios_updated_at on public.funcionarios;
create trigger set_funcionarios_updated_at before update on public.funcionarios
for each row execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_rotinas_updated_at on public.rotinas;
create trigger set_rotinas_updated_at before update on public.rotinas
for each row execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_tarefas_updated_at on public.tarefas;
create trigger set_tarefas_updated_at before update on public.tarefas
for each row execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_usuarios_updated_at on public.usuarios;
create trigger set_usuarios_updated_at before update on public.usuarios
for each row execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_configuracoes_updated_at on public.configuracoes;
create trigger set_configuracoes_updated_at before update on public.configuracoes
for each row execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_cenarios_updated_at on public.cenarios;
create trigger set_cenarios_updated_at before update on public.cenarios
for each row execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_auditoria_updated_at on public.auditoria;
create trigger set_auditoria_updated_at before update on public.auditoria
for each row execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_alertas_resolvidos_updated_at on public.alertas_resolvidos;
create trigger set_alertas_resolvidos_updated_at before update on public.alertas_resolvidos
for each row execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_alertas_adiados_updated_at on public.alertas_adiados;
create trigger set_alertas_adiados_updated_at before update on public.alertas_adiados
for each row execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_consumo_suplementacao_updated_at on public.consumo_suplementacao;
create trigger set_consumo_suplementacao_updated_at before update on public.consumo_suplementacao
for each row execute function public.set_current_timestamp_updated_at();
